### ISSUE TITLE
Create the robot battery power indicator interface

### ISSUE THREAD

**Issue by mcolinj** [FRC1076/RobotKitLib#31]
I think this is basically an AnalogInput() equivalent for wpilib, so you'll want to check the documentation for that (Issue #22  to get the interface correct.    Of course, we only have one of these, and it is fixed to a certain pin.

since, this is really not a general purpose analog pin (I'm not certain we have those available), you could wrap this
with a different thing that we actually would use, like maybe a Power Distribution Board.

class PDB:
    def __init__(self):
        self.adc = AnalogInput(Robot.BatteryVoltageADCPin)

    def getVoltage(self):
        return self.adc.getVoltage() * N     (what is N?   See if you can figure that out.)

So, in the run.py (or in robot.py) it would just get created and it would just periodically read(), and publish the value to a place in NetworkTables so that the driverstation can get it regularly.     We could set it every robot cycle for now, maybe less frequently if we start to see things slowing down.

You'll need to publish the NetworkTables attribute name in some documentation so that the driverstation implementor can know what value to read.

**Comment by EmilyRobotics** [comment]
I think this falls under the analog input issue now
