### ISSUE TITLE
Uploading code to the robot

### ISSUE THREAD

**Issue by EmilyRobotics** [FRC1076/RobotKitLib#48]
Todo issues:
Error handling (logging errors from code, logging if the robot file is broken (such as doesnt exist)

Fixing the driver station sending code to the robot
Fixing the driverstation incorrectly marking as no comms
Fixing the driverstation not having comms when it should have

**Comment by mcolinj** [comment]
Note, any computer on the robot network can send code to the robot.   It needn't be the driverstation.   In practice it has not been, it has been a developer laptop.    So, that shouldn't be a constraint.

The robot.py base in wpilib has a bunch of services that it provides.    Likely the best course of action is to look at that code and import it into our library with modifications.      "deploy" basically just copies all of the files in the current directory and all subdirectories, and copies them to a well-known place on the robot, and then it kicks the run.py to pick up the new code.       "install"  is a tool that would let you install python libraries on the pi without logging in to the pi.    That can all be very useful.    If you need help finding the code that already does this, speak up!
