### ISSUE TITLE
Add version info to driverstation and robot

### ISSUE THREAD

**Issue by VeeBallbach** [FRC1076/RobotKitLib#66]
Right now, it's really hard to tell if the robot and the driverstation laptop are running the same version of the code. At the very least, the driverstation should display a version, and robot_setup.py should print the version when it's run.  Preferably, there should be a version check between the robot and the driverstation to ensure that both are running the same code version, and to prevent the code from running if it doesn't match.

**Comment by EmilyRobotics** [comment]
completed on rework branch
